### PR TITLE
Sphinx workflow

### PR DESCRIPTION
**Pull request by engrosamaali91**
In order to setup a GitHub Workflow we require gh-pages in fastsurfer repository where html pages will be deployed.

### CODE REVIEW

File: CerebNet/data_loader/augmentation.py [hunk 1]
```diff
@@ -333,14 +333,14 @@ def sample_intensity_stats_from_image(
 
     Parameters
     ----------
-    image : array_like
+    image : np.ndarray
```
Comment (dkuegler) [inline CerebNet/data_loader/augmentation.py]: that is not the same, can you check whether this can be fixed?

File: CerebNet/utils/metrics.py [hunk 2]
```diff
@@ -194,10 +194,10 @@ def hd(result, reference, voxelspacing=None, connectivity=1):
 
     Parameters
     ----------
-    result : array_like
+    result : np.ndarray
```
Comment (dkuegler) [inline CerebNet/utils/metrics.py]: array_like is not the same as ndarray

File: .github/workflows/doc.yml [hunk 3]
```diff
@@ -0,0 +1,63 @@
...
+        shell: bash
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v4
+        with:
+          path: ./dev
+      - name: Setup Python 3.9
+        uses: actions/setup-python@v5
+        with:
+          python-version: 3.9
```
Comment (dkuegler) [inline .github/workflows/doc.yml]: I think this should be python 3.10
```suggestion
          python-version: 3.10
```

File: .github/workflows/doc.yml [hunk 4]
```diff
@@ -0,0 +1,63 @@
+name: doc
+concurrency:
+  group: ${{ github.workflow }}-${{ github.event.number }}-${{ github.event.ref }}
+  cancel-in-progress: true
+on:
+  pull_request:
+  push:
+    branches: [dev]
```
Comment (dkuegler) [inline .github/workflows/doc.yml:8]: on release, there should probably also be a build of the doc

- dev should always replace the old dev, but release are only ever built once (of the stable branch then).

File: doc/conf.py [hunk 5]
```diff
@@ -7,24 +7,22 @@
...
-sys.path.append(os.path.dirname(__file__) + '/..') 
-sys.path.append(os.path.dirname(__file__) + '/../recon_surf') 
+sys.path.append(os.path.dirname(__file__) + "/..")
+sys.path.append(os.path.dirname(__file__) + "/../recon_surf")
 
-project = 'FastSurfer'
-copyright = '2023, Martin Reuter'
-author = 'Martin Reuter'
+project = "FastSurfer"
+copyright = "2023, Martin Reuter"
```
Comment (dkuegler) [inline doc/conf.py]: I don't know how specifically this should be changed, maybe @m-reuter can say, but martin does not have the copyright on "all" of FastSurfer. I would say it makes more sense to say "FastSurfer Team" here or something.

Similarly, there is not just Martin as the author, but a couple of people.

File: doc/overview/CODE_OF_CONDUCT.md
Comment (dkuegler) [inline doc/overview/CODE_OF_CONDUCT.md:1]: It seems these files are added, inmost cases, the correct operation is to move these files. They are also still in the root directory of the project.

File: doc/overview/Docker/README.md
Comment (dkuegler) [inline doc/overview/Docker/README.md:1]: This file can stay in folder `Docker` for now.

File: doc/overview/EDITING.md
Comment (dkuegler) [inline doc/overview/EDITING.md:1]: should be moved, not copied

File: doc/overview/INSTALL.md
Comment (dkuegler) [inline doc/overview/INSTALL.md:1]: move not copy

File: doc/overview/README.md
Comment (dkuegler) [inline doc/overview/README.md:1]: It looks like this file was copied, but it should not.
1. some of the information in this file should stay in the README.md in the root folder.
2. This is **the** overview file. The other files are in a "overview" folder, which is fine I guess, but they could also be in the the folder `doc`.

So the file that remains in the root folder, should probably have some general information about FastSurfer, but then it can also have several links to files to get more information. I suspect I will have to edit some of this into the `<root>/README.md` file... I guess I have to look into this.

Maybe you can just move all the Examples into its own file, maybe even make dedicated files for each example?
All the information about the flags should be in one file. Another file should be the output files documentation. Then hardware requirements, maybe also modules.

File: doc/overview/Singularity/README.md
Comment (dkuegler) [inline doc/overview/Singularity/README.md:1]: stays in Singularity

File: doc/overview/SECURITY.md
Comment (dkuegler) [inline doc/overview/SECURITY.md:1]: move not copy

**Review by dkuegler — CHANGES_REQUESTED** [review]
Importantly, move not copy.

File: .github/workflows/doc.yml (hunk 4 above)
Comment (m-reuter) [reply .github/workflows/doc.yml:8]: currently (in our other repositories) we build on PRs and pushes to our development branch. That way the documentation always reflects the current dev version. Since doc strings are for developers mainly this makes most sense. In order to store (and not replace) webpages for releases, we would need to setup a more complex procedure, where we create a copy of the webpage from dev into a stable directory. Currently this has to be done manually.

File: doc/overview/README.md
Comment (engrosamaali91) [reply doc/overview/README.md:1]: The main README.md file is now split into three files
- FASTSURFER_EXAMPLES.md (Contains all six examples)
- FASTSURFER_FLAGS.md (Flags)
- FASTSURFER_OUTFUT_FILES.md

File: doc/conf.py (hunk 5 above)
Comment (m-reuter) [reply doc/conf.py]: Yes, you can say "2024, FastSurfer Developers" . Also I think we do not need an author field here, so that can be dropped.

File: doc/conf.py [hunk 6]
```diff
@@ -21,11 +21,8 @@
 sys.path.append(os.path.dirname(__file__) + "/../recon_surf")
 
 project = "FastSurfer"
-copyright = "2023, Martin Reuter"
-author = "Martin Reuter"
+author = "FastSurfer Developers"
 copyright = f"{date.today().year}, {author}"
```
Comment (dkuegler) [inline doc/conf.py]:
```suggestion
copyright = f"2020, {author}"
```

**Review by dkuegler — APPROVED** [review]

**Comment by dkuegler** [comment]
1. rebase on upstream
2. Docker and Singularity Files: 
    1. Remove the files in doc/overview
    2. Update the Links in other Markdown files
3. Examples etc.
   1. rename FASTSURFER_EXAMPLES.md to EXAMPLES.md (and other FASTSURFER_* files)
   2. update the links to examples etc. in all Markdown files (examples moved from README.md to doc/overview/FASTSURFER_EXAMPLES.md)

File: doc/conf.py [hunk 7]
```diff
@@ -21,11 +21,9 @@
 sys.path.append(os.path.dirname(__file__) + "/../recon_surf")
 
 project = "FastSurfer"
-copyright = "2023, Martin Reuter"
-author = "Martin Reuter"
+copyright = "2024, FastSurfer Team"
+author = "FastSurfer Team"
 copyright = f"{date.today().year}, {author}"
```
Comment (engrosamaali91) [inline doc/conf.py]:
```suggestion
author = "FastSurfer Developers"
copyright = f"2020, {author}"
```

File: .github/workflows/doc.yml [hunk 8]
```diff
@@ -0,0 +1,63 @@
...
+        shell: bash
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v4
+        with:
+          path: ./dev
+      - name: Setup Python 3.10
+        uses: actions/setup-python@v5
+        with:
+          python-version: 3.10
```
Comment (m-reuter) [inline .github/workflows/doc.yml]: probably need to be : ```python-version: '3.10' ```

Comment (dkuegler) [reply .github/workflows/doc.yml]:
```suggestion
          python-version: '3.10'
```

**Review by dkuegler — CHANGES_REQUESTED** [review]
As stated in PR.

File: pyproject.toml [hunk 9]
```diff
@@ -47,7 +47,28 @@ dependencies = [
     'torchio>=0.18.83',
     'tqdm>=4.64',
 ]
-
+doc = [
```
Comment (m-reuter) [inline pyproject.toml:51]:
```suggestion
[project.optional-dependencies]
doc = [
```

File: pyproject.toml [hunk 10]
```diff
@@ -47,7 +47,28 @@ dependencies = [
...
+    'pypandoc',
+    'nbsphinx',
+    'IPython', # For syntax highlighting in notebooks
+    'ipykernel',
+]
+all = [
+    'fastsurfer[doc]'
+]
+full = [
+    'fastSurfer[all]',
```
Comment (m-reuter) [inline pyproject.toml]:
```suggestion
    'fastsurfer[all]',
```

**Review by dkuegler — APPROVED** [review]

File: pyproject.toml [hunk 11]
```diff
@@ -47,9 +47,38 @@ dependencies = [
...
+    'sphinx-design',
+    'sphinx-gallery',
+    'sphinx-issues',
+    'pypandoc',
+    'nbsphinx',
+    'IPython', # For syntax highlighting in notebooks
+    'ipykernel',
+    'scikit-image',
+    'torchvision',
+    'sklearn',
```
Comment (dkuegler) [inline pyproject.toml]:
```suggestion
    'scikit-learn',
```

**Comment by dkuegler** [comment]
We are finally at a stage where the build works and the error is because of something completely different. In this case, the download_checkpoints.py script is broken, because it was not updated by #467 .

**Comment by m-reuter** [comment]
What still needs to be done here: 

- [x] Import of download_checkpoints fails as it gets `ImportError: cannot import name 'VINN_AXI' from 'FastSurferCNN.utils.checkpoint'` and other similar things. This needs to be fixed in dev (@agirodi ), then we rebase here.
- [x] doc/overview/FASTSURFER_EXAMPLES.md etc still exist and seem to be duplicates, check, merge (if necessary) and delete duplicates. FASTSURFER_EXAMPLES should be deleted , EXAMPLES.md kept, same with the other two.
- [ ] also doc/overview/README.md and the other md files replicate content of /README.md? So this means updating both files all the time? We need to discuss a solution for this. 
- [x] directory /doc/_static needs to be created (with `.gitkeep` empty file in it) as sphinx is looking for it. 
- [x] no idea what to do with the futures formatting warnings: ```concurrent.futures._base.Executor.map:15: WARNING: Inline emphasis start-string without end-string.``` , anyone? Why is sphinx even looking at those as they are not part of our project?

**Comment by dkuegler** [comment]
>     * [ ]  no idea what to do with the futures formatting warnings: `concurrent.futures._base.Executor.map:15: WARNING: Inline emphasis start-string without end-string.` , anyone? Why is sphinx even looking at those as they are not part of our project?

That is even a private module of `concurrent.futures`.

**Comment by dkuegler** [comment]
Maybe we can fix this warning with the autodoc_mock_imports directive?
> Add a list of modules in the [autodoc_mock_imports](https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html#confval-autodoc_mock_imports) to prevent import errors to halt the building process when some external dependencies are not importable at build time.

File: FastSurferCNN/utils/common.py [hunk 12]
```diff
@@ -1075,7 +1074,7 @@ def is_file(p: Path):
             return all(pool.map(is_file, self._subjects))
 
 
-class SerialExecutor(Executor):
+class SerialExecutor:
```
Comment (dkuegler) [inline FastSurferCNN/utils/common.py]:
```suggestion
class SerialExecutor(Executor):
```
Revert inheritance

**Review by m-reuter — APPROVED** [review]
